/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : test.c
*  Description  : Main Program
*  Creation Date: 2026-04-27
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include<stdio.h>

void main(void);

void main(void)
{
	printf("Hello.world\n");
	printf("1");
	printf("2");
}
